### ISSUE TITLE
Complexity of merge method in merge sort in O(n^2)

### ISSUE THREAD

**Issue by darhonbek** [sukhrobkhakimov/data-structures-and-algorithms#1]
**Problem:**
Due to usage of [remove(at:)](https://developer.apple.com/documentation/swift/array/1641390-remove) method, the complexity of merge function becomes O(n^2).
**Solution:**
Simply use iteration with indices over 2 arrays, without removing any elements.

**Comment by sukhrobkhakimov** [comment]
Your #3 PR fixes this issue
